import type { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    form
}: Readonly<{
    children: React.ReactNode
    form: React.ReactNode
}>) {
    return <>
        {form}
        {children}
    </>
}