import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.sass";
import { Suspense } from "react";
import Loading from "./loading";

const quicksand = Quicksand({ 
  subsets: ["latin"],
  weight:['300','400','500','700'] 
});

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>
    <html lang="en">
      <body className={quicksand.className }>
        <Suspense fallback={<Loading/>}>
          {children}
        </Suspense>
      </body>
    </html>
  </>
  
}
